engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
    config: config/coffeelint.json
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  eslint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  rubymotion:
    enabled: true
  scss-lint:
    enabled: true

ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- app/assets/javascripts/lib/jquery.*
- spec/**/*
- "**/vendor/**/*"
- db/schema.rb