require: rubocop-rspec
AllCops:
  Exclude:
  - vendor/**/*
  - spec/fixtures/**/*
  - tmp/**/*
  - db/schema.rb
  - m3/**/*
  TargetRailsVersion: 4.2
  TargetRubyVersion: 2.4
Bundler/OrderedGems:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - Rakefile
  - '**/*.rake'
  - spec/**/*.rb
  - config/routes.rb
  - Guardfile
  - db/migrate/*.rb
  ExcludedMethods:
  - default_form
  - class_methods
  - included
  - new
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/LineLength:
  Exclude:
  - Gemfile
  - db/migrate/*
  Max: 120
Metrics/MethodLength:
  Exclude:
  - db/migrate/*.rb
  Max: 30
Metrics/PerceivedComplexity:
  Max: 15
RSpec/AnyInstance:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
  - spec/controllers/m3_index_structure_spec.rb
  - spec/features/**/*
RSpec/EmptyExampleGroup:
  Exclude:
  - spec/rails_helper.rb
RSpec/ExampleLength:
  Max: 120
RSpec/LetSetup:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
Rails:
  Enabled: true
Rails/ApplicationRecord:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/Output:
  Exclude:
  - config/deploy/**/*
Rails/SkipsModelValidations:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
  - config/application.rb
  - config/boot.rb
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/SafeNavigation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
