
tcount = 0
youth_tag = PersonTag.find_by(name: 'U20')
Team.all.each do |t|
  next if t.tags.count .zero?
  tcount += 1
  p t
  (1..8).each do |i|
    person = Person.create!(team: t, last_name: Faker::Name.last_name, first_name: "#{Faker::Name.first_name} #{i}", gender: t.gender, bib_number: "#{tcount}#{i}")
    person.tags.push(youth_tag) if [0, 1, 1, 1].sample .zero?
    person.save!
    Assessment.requestable_for(person).each do |assessment|
      person.requests.create(assessment: assessment)
    end
  end
end

Team.find_by(gender: 0, name: 'FF Benndorf', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Boßdorf', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Gresse', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Groß Lübbenau', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Losenrade', number: 1).update!(lottery_number: 5)
Team.find_by(gender: 0, name: 'FF Lüderitz', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Markranstädt', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Missen', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Neusiß', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Neutrebbin', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Packebusch', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Staven', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Taura', number: 1).update!(lottery_number: 6)
Team.find_by(gender: 0, name: 'FF Tüttleben', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'FF Wusterhusen', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'Stadt Rostock', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 0, name: 'Team Brandenburg', number: 1).update!(lottery_number: 2)
Team.find_by(gender: 0, name: 'Team Brandenburg', number: 2).update!(lottery_number: 4)
Team.find_by(gender: 0, name: 'Team Brandenburg', number: 3).update!(lottery_number: 7)
Team.find_by(gender: 0, name: 'Team Mecklenburg-Vorpommern', number: 1).update!(lottery_number: 3)
Team.find_by(gender: 0, name: 'Team Mecklenburg-Vorpommern', number: 2).update!(lottery_number: 1)
Team.find_by(gender: 1, name: 'FF Altentreptow', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Drosa', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Gamstädt', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Genschmar', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Gera-Liebschwitz', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Hohen Viecheln', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Klein Radden', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Kleinbardau', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Mahitzschen', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Niederalbertsdorf', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Roxförde', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Stücken', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Tryppehna', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'FF Zella', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Stadt Berlin', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Stadt Berlin', number: 2).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Stadt Berlin', number: 3).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Stadt Rostock', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Team Landkreis Rostock', number: 1).update!(lottery_number: nil)
Team.find_by(gender: 1, name: 'Team Lausitz', number: 1).update!(lottery_number: 10)
Team.find_by(gender: 1, name: 'Team Lausitz', number: 2).update!(lottery_number: 1)
Team.find_by(gender: 1, name: 'Team Mecklenburg-Vorpommern', number: 1).update!(lottery_number: 4)
Team.find_by(gender: 1, name: 'Team Mecklenburg-Vorpommern', number: 2).update!(lottery_number: 9)
Team.find_by(gender: 1, name: 'Team Märkisch-Oderland', number: 1).update!(lottery_number: 7)
Team.find_by(gender: 1, name: 'Team Sachsen', number: 1).update!(lottery_number: 8)
Team.find_by(gender: 1, name: 'Team Sachsen', number: 2).update!(lottery_number: 5)
Team.find_by(gender: 1, name: 'Team Sachsen', number: 3).update!(lottery_number: 3)
Team.find_by(gender: 1, name: 'Thüringen-Auswahl', number: 1).update!(lottery_number: 2)
Team.find_by(gender: 1, name: 'Thüringen-Auswahl', number: 2).update!(lottery_number: 6)

entries = Score::List.find(x).entries
entries.where(entity: Team.find_by(name: 'Team Brandenburg', gender: 0, number: 2)).update_all(run: 1, track: 1)
entries.where(entity: Team.find_by(name: 'FF Neusiß', gender: 0, number: 1)).update_all(run: 1, track: 2)
entries.where(entity: Team.find_by(name: 'Team Brandenburg', gender: 0, number: 1)).update_all(run: 1, track: 3)
entries.where(entity: Team.find_by(name: 'Stadt Rostock', gender: 0, number: 1)).update_all(run: 2, track: 1)
entries.where(entity: Team.find_by(name: 'FF Taura', gender: 0, number: 1)).update_all(run: 2, track: 2)
entries.where(entity: Team.find_by(name: 'FF Wusterhusen', gender: 0, number: 1)).update_all(run: 2, track: 3)
entries.where(entity: Team.find_by(name: 'FF Benndorf', gender: 0, number: 1)).update_all(run: 3, track: 1)
entries.where(entity: Team.find_by(name: 'FF Neutrebbin', gender: 0, number: 1)).update_all(run: 3, track: 2)
entries.where(entity: Team.find_by(name: 'FF Lüderitz', gender: 0, number: 1)).update_all(run: 3, track: 3)
entries.where(entity: Team.find_by(name: 'FF Losenrade', gender: 0, number: 1)).update_all(run: 4, track: 1)
entries.where(entity: Team.find_by(name: 'Team Mecklenburg-Vorpommern', gender: 0, number: 2)).update_all(run: 4, track: 2)
entries.where(entity: Team.find_by(name: 'FF Boßdorf', gender: 0, number: 1)).update_all(run: 4, track: 3)
entries.where(entity: Team.find_by(name: 'Team Brandenburg', gender: 0, number: 3)).update_all(run: 5, track: 1)
entries.where(entity: Team.find_by(name: 'Team Mecklenburg-Vorpommern', gender: 0, number: 1)).update_all(run: 5, track: 2)
entries.where(entity: Team.find_by(name: 'FF Tüttleben', gender: 0, number: 1)).update_all(run: 5, track: 3)
entries.where(entity: Team.find_by(name: 'FF Packebusch', gender: 0, number: 1)).update_all(run: 6, track: 1)
entries.where(entity: Team.find_by(name: 'FF Gresse', gender: 0, number: 1)).update_all(run: 6, track: 2)
entries.where(entity: Team.find_by(name: 'FF Missen', gender: 0, number: 1)).update_all(run: 6, track: 3)
entries.where(entity: Team.find_by(name: 'FF Markranstädt', gender: 0, number: 1)).update_all(run: 7, track: 1)
entries.where(entity: Team.find_by(name: 'FF Groß Lübbenau', gender: 0, number: 1)).update_all(run: 7, track: 2)
entries.where(entity: Team.find_by(name: 'FF Staven', gender: 0, number: 1)).update_all(run: 7, track: 3)

entries = Score::List.find(y).entries
entries.where(entity: Team.find_by(name: 'FF Roxförde', gender: 1, number: 1)).update_all(run: 1, track: 1)
entries.where(entity: Team.find_by(name: 'Team Sachsen', gender: 1, number: 3)).update_all(run: 1, track: 2)
entries.where(entity: Team.find_by(name: 'Team Mecklenburg-Vorpommern', gender: 1, number: 2)).update_all(run: 1, track: 3)
entries.where(entity: Team.find_by(name: 'FF Gera-Liebschwitz', gender: 1, number: 1)).update_all(run: 2, track: 1)
entries.where(entity: Team.find_by(name: 'Team Mecklenburg-Vorpommern', gender: 1, number: 1)).update_all(run: 2, track: 2)
entries.where(entity: Team.find_by(name: 'Team Lausitz', gender: 1, number: 1)).update_all(run: 2, track: 3)
entries.where(entity: Team.find_by(name: 'FF Altentreptow', gender: 1, number: 1)).update_all(run: 3, track: 1)
entries.where(entity: Team.find_by(name: 'FF Mahitzschen', gender: 1, number: 1)).update_all(run: 3, track: 2)
entries.where(entity: Team.find_by(name: 'FF Drosa', gender: 1, number: 1)).update_all(run: 3, track: 3)
entries.where(entity: Team.find_by(name: 'Team Märkisch-Oderland', gender: 1, number: 1)).update_all(run: 4, track: 1)
entries.where(entity: Team.find_by(name: 'FF Kleinbardau', gender: 1, number: 1)).update_all(run: 4, track: 2)
entries.where(entity: Team.find_by(name: 'Thüringen-Auswahl', gender: 1, number: 2)).update_all(run: 4, track: 3)
entries.where(entity: Team.find_by(name: 'Team Landkreis Rostock', gender: 1, number: 1)).update_all(run: 5, track: 1)
entries.where(entity: Team.find_by(name: 'FF Stücken', gender: 1, number: 1)).update_all(run: 5, track: 2)
entries.where(entity: Team.find_by(name: 'FF Hohen Viecheln', gender: 1, number: 1)).update_all(run: 5, track: 3)
entries.where(entity: Team.find_by(name: 'Team Sachsen', gender: 1, number: 1)).update_all(run: 6, track: 1)
entries.where(entity: Team.find_by(name: 'FF Gamstädt', gender: 1, number: 1)).update_all(run: 6, track: 2)
entries.where(entity: Team.find_by(name: 'Team Lausitz', gender: 1, number: 2)).update_all(run: 6, track: 3)
entries.where(entity: Team.find_by(name: 'Thüringen-Auswahl', gender: 1, number: 1)).update_all(run: 7, track: 1)
entries.where(entity: Team.find_by(name: 'Stadt Berlin', gender: 1, number: 2)).update_all(run: 7, track: 2)
entries.where(entity: Team.find_by(name: 'FF Klein Radden', gender: 1, number: 1)).update_all(run: 7, track: 3)
entries.where(entity: Team.find_by(name: 'Stadt Rostock', gender: 1, number: 1)).update_all(run: 8, track: 1)
entries.where(entity: Team.find_by(name: 'FF Tryppehna', gender: 1, number: 1)).update_all(run: 8, track: 2)
entries.where(entity: Team.find_by(name: 'Team Sachsen', gender: 1, number: 2)).update_all(run: 8, track: 3)
entries.where(entity: Team.find_by(name: 'Stadt Berlin', gender: 1, number: 3)).update_all(run: 9, track: 1)
entries.where(entity: Team.find_by(name: 'FF Zella', gender: 1, number: 1)).update_all(run: 9, track: 2)
entries.where(entity: Team.find_by(name: 'FF Genschmar', gender: 1, number: 1)).update_all(run: 9, track: 3)
entries.where(entity: Team.find_by(name: 'FF Niederalbertsdorf', gender: 1, number: 1)).update_all(run: 10, track: 1)
entries.where(entity: Team.find_by(name: 'Stadt Berlin', gender: 1, number: 1)).update_all(run: 10, track: 2)
